### ISSUE TITLE
Error: Configuration property "dbConfig.host" is not defined

### ISSUE THREAD

**Issue by namdaik** [sagarankoliya/realtime-private-chat-nodejs-socketio-vuejs-laravel#9]
I have an error as follows
$ export NODE_ENV=dev
$ sudo npm start

WARNING: No configurations found in configuration directory:/var/www/chatvue.local/nodejs/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/var/www/chatvue.local/nodejs/node_modules/config/lib/config.js:202
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "dbConfig.host" is not defined
    at Config.get (/var/www/chatvue.local/nodejs/node_modules/config/lib/config.js:202:11)
    at new Db (/var/www/chatvue.local/nodejs/utils/db.js:10:17)
    at Object.<anonymous> (/var/www/chatvue.local/nodejs/utils/db.js:36:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by namdaik** [comment]
host: 'localhost',
			user: 'admin',
			password: 'adadad@aA',
			database: 'vue',
I fixed the db file and the application ran successfully

**Comment by namdaik** [comment]
![image](https://user-images.githubusercontent.com/19622562/49233973-b60de300-f429-11e8-94e2-e1f46beca6f5.png)
not have channel

**Comment by sagarankoliya** [comment]
Hii @namdaik,

I think you have create only one user please create two user minimum for chat.

Thanks,
Sagar
